# Generated by Django 4.2 on 2023-04-07 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medication_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=None, null=True)),
                ('usage_in_last_30_days', models.IntegerField(default=None, null=True)),
                ('remaining_day_supply', models.IntegerField(default=None, null=True)),
                ('is_identified', models.BooleanField(default=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('documented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
