# Generated by Django 4.2 on 2023-04-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medication_name', models.CharField(max_length=255)),
                ('usage_in_last_30_days', models.IntegerField()),
                ('remaining_day_supply', models.IntegerField()),
                ('is_identified', models.BooleanField(default='Yes')),
                ('is_confirmed', models.BooleanField(default='No')),
                ('is_resolved', models.BooleanField(default='No')),
                ('documented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
