# Generated by Django 4.2 on 2023-04-05 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortage',
            name='quantity',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shortage',
            name='documented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shortage',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shortage',
            name='is_identified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shortage',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shortage',
            name='remaining_day_supply',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shortage',
            name='usage_in_last_30_days',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
